services:
  api:
    build: ./backend
    container_name: app-backend
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "3001:3001"
    networks: 
     - backend_net
     - internal-app-net
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_USER: username
      MONGO_PASSWORD: password
      MONGO_DB: appdb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api"]
      interval: 10s
      timeout: 5s
      retries: 5
