services:
  mongo:
    image: mongo:7
    container_name: app-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_URI: mongodb://username:password@mongo:27017/appdb?authSource=admin

    volumes:
      - mongodb_data:/data/db
    networks:
      - db_net
      - internal-app-net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --username \"$MONGO_INITDB_ROOT_USERNAME\" --password \"$MONGO_INITDB_ROOT_PASSWORD\" --authenticationDatabase admin --eval \"db.adminCommand('ping')\" || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data: