services:
  nginx:
    image: nginx:alpine
    container_name: app-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot-conf:/etc/letsencrypt
    networks:
      - frontend_net

  certbot:
    image: certbot/dns-cloudflare
    container_name: certbot
    secrets:
      - cloudflare_api_token
    volumes:
      - certbot-conf:/etc/letsencrypt
    command: >
      certonly
      --dns-cloudflare
      --dns-cloudflare-credentials /run/secrets/cloudflare_api_token
      --dns-cloudflare-propagation-seconds 60
      --email deep.devopsnerd@gmail.com
      --agree-tos
      --no-eff-email
      -d todo-app.myrrhsolutions.in
      
networks:
  app-platform-net:
    name: app-platform-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16

  backend_net:
    name: backend_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.10.0/24

  db_net:
    name: db_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.20.0/24

  frontend_net:
    name: frontend_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.30.0/24

  internal-app-net:
    name: internal-app-net
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.30.100.0/24

secrets:
  cloudflare_api_token:
    file: ./secrets/cloudflare.ini

volumes:
  certbot-conf: